### ISSUE TITLE
playback 2x slower on obscure device

### ISSUE THREAD

**Issue by v1nc** [lichray/wavplay#1]
I want to play wav files on an proprietary and obscure device.
The device software includes wav files that it plays sometimes, but I dont know how. It looks like its using `/dev/dsp`
Alsa or any play command is not available on the device

Now wavplay is the first thing that can play any sound on it. 
Unfortunately the wav files are playing some kind of dully and around 2x slower than they should. 
I tried the files that are placed on the device and also speedup a file 2x without any luck.

All wavs i tried are `PCM 16 bit mono 48000 Hz`

What can I try to make it work?

**Comment by lichray** [comment]
This project does not do any resampling, so if the sound device falsely reports that it supports 48000 Hz sample rate, wavplay will just send the stream. I suggest you figure out what actual formats are supported by this hardware. If there is no product manual, maybe try more files with different sample rates and bit rates.

**Comment by v1nc** [comment]
Wow, that was really fast :3
I tried different sample rates and it finally works.

Thanks a lot for your work!
